### ISSUE TITLE
Enhancement Request: 80 Column ruler

### ISSUE THREAD

**Issue by modcap** [chenzhiwei/chrome-markdown-editor#7]
It is a pretty standard convention to line-break ascii docs at column 80, and it would be terrific if there was a checkbox in the options that can enable a simple line at column 80.

I have been using inspector to add the following class every time I use the editor:

```css

.CodeMirror-code {
    max-width: 82ch; /* for some reason I haven't researched setting to 80ch only allows 78 chars */
    border-right: 1px solid #eee;
}
```

I'm not sure if `.CodeMirror-code` would be the best choice for where to add this (a transparent absolutely positioned div may be better) but I think this would help a lot of readme/wiki editors.

Thanks for the great extension either way.
